# Generated by Django 5.2.5 on 2026-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
