# Generated by Django 5.2.5 on 2026-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
