# Generated by Django 5.1.7 on 2025-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
