# Generated by Django 5.2.1 on 2025-06-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_cartitem_options_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Tramitado'), ('shipped', 'Enviado')], default='pending', max_length=20),
        ),
    ]
