# Generated by Django 5.2.1 on 2025-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pendiente'), ('processed', 'procesado'), ('shipped', 'enviado')], default='pending', max_length=20),
        ),
    ]
