# Generated by Django 5.2.1 on 2025-07-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_cart_options_alter_cart_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='payments.transaction'),
        ),
    ]
