# Generated by Django 5.2.1 on 2025-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_cart_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
