# Generated by Django 5.2.1 on 2025-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_transaction_amount_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
