# Generated by Django 5.2.1 on 2025-07-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_cartitem_price_at_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_sale',
        ),
    ]
