# Generated by Django 5.2.5 on 2026-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_cartitem_price_at_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirming', 'Confirmando'), ('confirmed', 'Confirmada'), ('failed', 'Fallida')], default='pending', max_length=20),
        ),
    ]
