# Generated by Django 5.2.5 on 2026-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_add_confirming_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirming', 'Confirmando'), ('confirmed', 'Confirmada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
