## Generated by Django 5.2.5 on 2026-05-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_transaction_status'),
    ]

    operations = [
        # Eliminar el modelo Cart directamente (esto elimina la tabla y todas sus referencias)
        migrations.DeleteModel(
            name='Cart',
        ),
        # Eliminar el modelo CartItem directamente (esto elimina la tabla y todas sus referencias)
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]