# Generated by Django 5.2.5 on 2026-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_remove_cartitem_cart_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pendiente'), ('processed', 'procesado'), ('shipped', 'enviado'), ('cancelled', 'cancelado')], default='pending', max_length=20),
        ),
    ]
