# Generated by Django 5.2.5 on 2026-05-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_orderitem_status'),
    ]

    operations = [
    ]
